### ISSUE TITLE
Your blog is broken

### ISSUE THREAD

**Issue by RaymiiOrg** [boredzo/iso-8601-date-formatter#84]
Wasn't able to find an email address, lets try it this way.

Your blog gives an error:

    
```
Fatal error: __autoload() is no longer supported, use spl_autoload_register() instead in /home/public/blog/wp-includes/compat.php on line 502
```

https://boredzo.org/blog/

**Comment by boredzo** [comment]
Thanks. Will take a look today.

**Comment by boredzo** [comment]
Well, that took basically all day. Web host dropped PHP 7, so my long-put-off upgrade to a less-ancient WordPress could wait no longer. Then I had 404s most of the day because of a merge screw-up that caused wp_query to be unable to look up any posts.

It's fixed now. Thanks again for letting me now.

**Comment by RaymiiOrg** [comment]
> Well, that took basically all day. Web host dropped PHP 7, so my long-put-off upgrade to a less-ancient WordPress could wait no longer. Then I had 404s most of the day because of a merge screw-up that caused wp_query to be unable to look up any posts.
> 
> It's fixed now. Thanks again for letting me now.

Thank you for taking a look and fixing it!
